import { defineConfig } from 'eslint/config';

/**
 * Auto-generated by `npm run generate-typescript-compatibility-rules`.
 * Do not edit this file manually.
 * Disables core ESLint rules that are superseded by @typescript-eslint extensions
 * and mirrors their configuration onto the TypeScript equivalents.
 * Also applies manual TS-scoped overrides (see script `manualOverrides`).
 */
export const recommended = defineConfig({
  files: ['**/*.{ts,tsx}'],
  rules: {
    '@typescript-eslint/class-methods-use-this': 0,
    '@typescript-eslint/consistent-return': 2,
    '@typescript-eslint/default-param-last': 2,
    '@typescript-eslint/dot-notation': 2,
    '@typescript-eslint/init-declarations': 0,
    '@typescript-eslint/max-params': 0,
    '@typescript-eslint/no-array-constructor': 2,
    '@typescript-eslint/no-dupe-class-members': 2,
    '@typescript-eslint/no-implied-eval': 2,
    '@typescript-eslint/no-invalid-this': 0,
    '@typescript-eslint/no-loop-func': 2,
    '@typescript-eslint/no-loss-of-precision': 2,
    '@typescript-eslint/no-magic-numbers': 0,
    '@typescript-eslint/no-redeclare': [
      2,
      {
        builtinGlobals: true,
      },
    ],
    '@typescript-eslint/no-restricted-imports': 0,
    '@typescript-eslint/no-shadow': [
      2,
      {
        builtinGlobals: false,
        hoist: 'all',
      },
    ],
    '@typescript-eslint/no-unused-expressions': 2,
    '@typescript-eslint/no-unused-private-class-members': 0,
    '@typescript-eslint/no-unused-vars': 2,
    '@typescript-eslint/no-use-before-define': [
      2,
      {
        classes: true,
        functions: false,
        variables: true,
      },
    ],
    '@typescript-eslint/no-useless-constructor': 2,
    '@typescript-eslint/only-throw-error': 2,
    '@typescript-eslint/prefer-destructuring': 0,
    '@typescript-eslint/prefer-promise-reject-errors': 2,
    '@typescript-eslint/require-await': 0,
    'class-methods-use-this': 0,
    'consistent-return': 0,
    'default-param-last': 0,
    'dot-notation': 0,
    'init-declarations': 0,
    'max-params': 0,
    'no-array-constructor': 0,
    'no-dupe-class-members': 0,
    'no-implied-eval': 0,
    'no-invalid-this': 0,
    'no-loop-func': 0,
    'no-loss-of-precision': 0,
    'no-magic-numbers': 0,
    'no-redeclare': 0,
    'no-restricted-imports': 0,
    'no-shadow': 0,
    'no-throw-literal': 0,
    'no-unused-expressions': 0,
    'no-unused-private-class-members': 0,
    'no-unused-vars': 0,
    'no-use-before-define': 0,
    'no-useless-constructor': 0,
    'prefer-destructuring': 0,
    'prefer-promise-reject-errors': 0,
    'react/prop-types': 0,
    'require-await': 0,
  },
});
